sudo : required
services:
  - docker
before_install:
  - docker build -t shivakumarmarati/docker-react -f Dockerfile.dev . 
script:
  - docker run -e CI=true shivakumarmarati/docker-react npm run test   -- --coverage
language: generic   